# Generated by Django 5.0.3 on 2024-10-10 12:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("User_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("job_seeker", "job_seeker"), ("employer", "employer")],
                max_length=20,
            ),
        ),
    ]
